vich_uploader:
    db_driver: orm

    mappings:
        kitty_images:
            uri_prefix: '%app.path.kitty_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.kitty_images%'
