AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'bref-kitty-quotes-symfony'
            Description: ''
            CodeUri: .
            Handler: public/index.php
            Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
            MemorySize: 1024
            Runtime: provided
            Environment:
                Variables:
                    APP_ENV: prod
            Layers:
                - 'arn:aws:lambda:eu-west-1:209497400698:layer:php-73-fpm:1'
            Events:
                # The function will match all HTTP URLs
                HttpRoot:
                    Type: Api
                    Properties:
                        Path: /
                        Method: ANY
                HttpSubPaths:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY
                # The function will match all HTTP URLs
                AdminHttpRoot:
                    Type: Api
                    Properties:
                        Path: /admin/
                        Method: ANY
                AdminHttpSubPaths:
                    Type: Api
                    Properties:
                        Path: /admin/{proxy+}
                        Method: ANY
                # The function will match all HTTP URLs
                LoginHttpRoot:
                    Type: Api
                    Properties:
                        Path: /login
                        Method: ANY
                LoginHttpSubPaths:
                    Type: Api
                    Properties:
                        Path: /login/{proxy+}
                        Method: ANY

# Outputs show up in the CloudFormation dashboard
Outputs:
    DemoHttpApi:
        Description: 'URL of our function in the *Prod* environment'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
